version: "3.8"

services:
  puppet:
    image: puppet/puppetserver
    env_file: env/puppet.env
    restart: always
    ports:
      - 8140:8140

  puppetdb:
    image: puppet/puppetdb
    env_file: env/puppetdb.env
    restart: always
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - puppet
      - postgres

  postgres:
    image: postgres:9.6.15
    env_file: env/postgres.env
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432:5432

  puppet-agent:
    image: puppet/puppet-agent
    depends_on:
      - puppet
      - puppetdb
